image: alpine/edge
packages:
  - nodejs
  - npm
  - hut
oauth:
  pages.sr.ht/PAGES:RW
environment:
  site: alejandrolaguna.srht.site
tasks:
  - install: |
      cd portfolio
      npm ci
  - build: |
      cd portfolio
      npm run build
  - package: |
      cd portfolio
      tar -C dist -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
